# Copyright 2008-present Contributors to the OpenImageIO project.
# SPDX-License-Identifier: BSD-3-Clause
# https://github.com/OpenImageIO/oiio

name: CI

on:
  push:
    # Skip jobs when only documentation files are changed
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'
  schedule:
    # Full nightly build
    - cron: "0 8 * * *"


jobs:
  linux-oldest:
    # Oldest versions of the dependencies that we can muster, and various
    # things disabled (no SSE, OCIO, or OpenCV, don't embed plugins).
    name: "Linux oldest/hobbled: gcc6.3/C++14 py2.7 boost-1.66 exr-2.3 no-sse no-ocio"
    runs-on: ubuntu-latest
    container:
      image: aswf/ci-osl:2019
    env:
      CMAKE_CXX_STANDARD: 14
      USE_SIMD: 0
      USE_JPEGTURBO: 0
      USE_OPENCOLORIO: 0
      USE_OPENCV: 0
      EMBEDPLUGINS: 0
      FMT_VERSION: 6.1.2
      OPENEXR_VERSION: v2.3.0
      PTEX_VERSION: v2.3.1
      PYBIND11_VERSION: v2.4.2
      WEBP_VERSION: v1.0.0
    steps:
      - uses: actions/checkout@v2
      - name: Prepare ccache timestamp
        id: ccache_cache_keys
        run: |
          echo "::set-output name=date::`date -u +'%Y-%m-%dT%H:%M:%SZ'`"
      - name: ccache
        id: ccache
        uses: actions/cache@v2
        with:
          path: /tmp/ccache
          key: ${{ github.job }}-${{ steps.ccache_cache_keys.outputs.date }}
          restore-keys: |
            ${{ github.job }}-
      - name: Build setup
        run: |
            src/build-scripts/ci-startup.bash
      - name: Dependencies
        run: |
            sudo rm -rf /usr/local/include/OpenEXR
            src/build-scripts/gh-installdeps.bash
      - name: Build
        run: |
            src/build-scripts/ci-build.bash
      - name: Testsuite
        run: |
            src/build-scripts/ci-test.bash
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}
          path: |
            build/CMake*.{txt,log}
            build/testsuite/*/*.*
            !build/testsuite/oiio-images
            !build/testsuite/openexr-images
            !build/testsuite/fits-images
            !build/testsuite/j2kp4files_v1_5
